apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronos-consumer-dlq
  labels:
    {{- include "kronos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumerDlq.replicas }}
  selector:
    matchLabels:
      app: kronos-consumer-dlq
  template:
    metadata:
      labels:
        app: kronos-consumer-dlq
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup kronos-kafka.default.svc.cluster.local; do echo waiting for kafka; sleep 2; done']
      containers:
        - name: consumer-dlq
          image: "{{ .Values.consumerDlq.image }}:{{ .Values.consumerDlq.tag }}"
          imagePullPolicy: Never
          args: ["-kafka-broker={{ .Values.kafka.broker }}"]