apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kronos-grpc-server
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: kronos-grpc-server
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kronos-consumer-analytics
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: kronos-consumer-analytics
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics