# argocd/kronos-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kronos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cotishq/kronos
    targetRevision: HEAD
    path: charts/kronos
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true